// Meta Data
export const metadata = {
    // Title & Descriptions
    title: "Order - Creative Logo Designs",
    description: "Generated by Creative Logo Designs",
    // Google Varification
    verification: {
        google: 'ziIYRBahP4WcKcps6RWRDJvZ9A00pSoI39ByXDN14us',
        other: {
            "facebook-domain-verification": ['rfth5fqyv2is1cegfmcloebw46z7nz'],
        },
    },
    // Canonical
    alternates: {
        canonical: 'https://www.creativelogodesigns.io/order',
    }
}

export default function RootLayout({ children }) {
    return (children);
}