import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request) {
    try {
        const { name, email, phone, service, message, pageURL } = await request.json();
        const transporter = nodemailer.createTransport({
            service: "gmail",
            host: "smtp.gmail.com",
            port: 465,
            secure: true,
            auth: {
                user: 'dev.mr@production-dev.com',
                pass: "devmrqwer@1234"
            }
        });
        const mailOptions = {
            from: 'dev.mr@production-dev.com',
            to: 'dev.mr@production-dev.com',
            subject: `New Lead Generated By Creative Logo Designs`,
            html: `<table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        ${service && <th>Service</th>}
                        <th>Message</th>
                        <th>URL</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>${name}</td>
                        <td>${email}</td>
                        <td>${phone}</td>
                        ${service && <td>${service}</td>}
                        <td>${message}</td>
                        <td>${pageURL}</td>
                    </tr>
                </tbody>
            </table>`
        };
        await transporter.sendMail(mailOptions);
        return NextResponse.json({ "mesaage": "Email sent successfully", "status": 200 });
    } catch (error) {
        return NextResponse.json({ "mesaage": "Failed to sent Email", "status": 500 });
    }
}